---
- name: Set up Caddy prerequisites
  ansible.builtin.import_tasks: setup.yml
  tags: service_caddy_setup

- name: Deploy Caddy stack
  ansible.builtin.import_tasks: deploy.yml
  tags: service_caddy_deploy
