---
# General variables for all hosts

# SSH port — single source of truth
baseline_config_ssh_port: 4343
ansible_port: "{{ baseline_config_ssh_port }}"

# Admin user
baseline_config_admin_users:
  - name: hbadmin
    ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHWyoRMlrra8cqK8ftcSLVSKTTNrcFX3qIW82oU9HRU hbadmin"

# Service user
service_caddy_user: hbadmin
service_nextcloud_user: hbadmin

# Caddy — Let's Encrypt email
service_caddy_email: "alexander.baer02+letsencrypt@gmail.com"

# Authelia
service_authelia_domain: "auth.nexus4-2.de"
service_authelia_cookie_domain: ".nexus4-2.de"

# Service domains
service_nextcloud_domain: "nextcloud.nexus4-2.de"
service_vaultwarden_domain: "vault.nexus4-2.de"
service_paperless_domain: "paperless.nexus4-2.de"
service_jitsi_domain: "meet.nexus4-2.de"
service_wordpress_domain: "wp.nexus4-2.de"

# Vaultwarden — disable admin panel
service_vaultwarden_admin_token: ""
