---
# Vault-encrypted secrets â€” placeholders
# Encrypt with: ansible-vault encrypt_string

# SSH public key for Ansible user
vault_ansible_ssh_pubkey: "PLACEHOLDER_SSH_PUBKEY"

# SSH public keys for admin users
vault_alex_ssh_pubkey: "PLACEHOLDER_SSH_PUBKEY_ALEX"
vault_sina_ssh_pubkey: "PLACEHOLDER_SSH_PUBKEY_SINA"

vault_nextcloud_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65393333303930303733346234663663376561353530633837373635363832666264363438386532
          6331363535633966633537366561303535363839663162340a343335386461653863373236323563
          63373562323465376264343965383231333539623233613965333830643766666665356438363666
          3137373737376531350a333538326636323366643663353932636464353132356666396563306630
          62623562386231386562393638613432623738366632643965646466303235363666336330616635
          39383433353565373131633935653333363236623461613430306264333034616333646137383030
          39343735303461346661346161383330633233393737346338353432656633666536396433353739
          32393666323737343538
vault_nextcloud_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66316535663330616164396631383166366263333065363331616233336632356231663239303934
          6434613232333937393236653863313161626535653865390a313064336439356263363232303763
          34613064393062636538343066633032313066396432333837326439623232316430366666353938
          6532313533656133380a653237363163663231363130323466383862633534316565663032613935
          61613231626563666634356437633533353030386163323661613537373166643562316661663266
          39323234663030346130663338633439363562323966396362373535653332396237636433636263
          64626464396165636564356566383139343536326338326663643530366164323037363864663534
          36646337326636323665
