---
- name: Restart vaultwarden
  ansible.builtin.shell:
    cmd: podman-compose down && podman-compose up -d
    chdir: "{{ service_vaultwarden_base_dir }}"
  become: true
  become_user: "{{ service_vaultwarden_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ service_vaultwarden_uid }}"
  changed_when: false

- name: Reload caddy for vaultwarden
  ansible.builtin.command:
    cmd: podman exec caddy caddy reload --config /etc/caddy/Caddyfile
  become: true
  become_user: "{{ service_caddy_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ service_vaultwarden_caddy_uid }}"
  changed_when: false
