---
- name: Fail2ban installieren
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Fail2ban Jail-Konfiguration deployen
  ansible.builtin.template:
    src: fail2ban_jail_local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Fail2ban aktivieren und starten
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
