---
- name: Configure users
  ansible.builtin.import_tasks: users.yml
  tags: users

- name: Harden SSH
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Configure NTP
  ansible.builtin.import_tasks: ntp.yml
  tags: ntp

- name: Apply kernel hardening (sysctl)
  ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- name: Configure Fail2ban
  ansible.builtin.import_tasks: fail2ban.yml
  tags: fail2ban

- name: Configure unattended upgrades
  ansible.builtin.import_tasks: unattended_upgrades.yml
  tags: unattended_upgrades

- name: Configure logging
  ansible.builtin.import_tasks: logging.yml
  tags: logging

- name: Install and configure Podman
  ansible.builtin.import_tasks: podman.yml
  tags: podman
