---
- name: Unattended-Upgrades installieren
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Unattended-Upgrades — Sicherheitsupdates aktivieren
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//\s*"\$\{distro_id\}:\$\{distro_codename\}-security";'
    line: '        "${distro_id}:${distro_codename}-security";'
    state: present

- name: Unattended-Upgrades — Auto-Reboot konfigurieren
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^.*Unattended-Upgrade::Automatic-Reboot\s'
    line: 'Unattended-Upgrade::Automatic-Reboot "{{ baseline_config_unattended_reboot | lower }}";'
    state: present

- name: Unattended-Upgrades — Reboot-Zeitpunkt konfigurieren
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^.*Unattended-Upgrade::Automatic-Reboot-Time'
    line: 'Unattended-Upgrade::Automatic-Reboot-Time "{{ baseline_config_unattended_reboot_time }}";'
    state: present

- name: Automatische Updates aktivieren
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"
