---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Enable security updates
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?"\$\{distro_id\}:\$\{distro_codename\}-security";'
    line: '        "${distro_id}:${distro_codename}-security";'
    state: present
    backup: true

- name: Configure automatic reboot policy
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?Unattended-Upgrade::Automatic-Reboot\s'
    line: 'Unattended-Upgrade::Automatic-Reboot "{{ baseline_config_unattended_reboot | lower }}";'
    state: present
    backup: true

- name: Configure automatic reboot time
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?Unattended-Upgrade::Automatic-Reboot-Time'
    line: 'Unattended-Upgrade::Automatic-Reboot-Time "{{ baseline_config_unattended_reboot_time }}";'
    state: present
    backup: true

- name: Enable automatic updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"
