---
# Vault-verschluesselte Secrets â€” Platzhalter
# Verschluesselung: ansible-vault encrypt inventories/production/group_vars/all/vault.yml

# SSH Public Key des ansible-Users
vault_ansible_ssh_pubkey: "PLATZHALTER_SSH_PUBKEY"

# Gehashtes Passwort des ansible-Users (optional)
# Erstellen mit: mkpasswd --method=sha-512
vault_ansible_user_password: "PLATZHALTER_PASSWORT_HASH"
