---
- name: Baseline server configuration and hardening
  hosts: test_servers
  become: true

  roles:
    - baseline_config
    - service_caddy
    - service_authelia
    - service_nextcloud
    - service_vaultwarden
    - service_paperless
    - service_jitsi
